<?php
declare(strict_types=1);

// A minimal, pure-PHP PDF text reader — no Imagick, no `exec`/pdftotext,
// no Composer package. Shared hosting can't be relied on to have any of
// those, but `zlib` (gzuncompress) ships with PHP itself, which is enough
// to decode the FlateDecode content streams that make up the vast
// majority of real, computer-generated insurer PDFs.
//
// What this can and cannot read, on purpose:
//  * Reads: ordinary single-object-per-stream PDFs (practically every
//    insurer e-policy / policy schedule generated by software).
//  * Does NOT read: scanned or photographed policy documents (there is no
//    OCR engine here), or PDFs using compressed cross-reference/object
//    streams (PDF 1.5+ "ObjStm" layout) — those need a real PDF library.
//  * When it can't find much text, it says so (`low_confidence`) instead
//    of guessing at financial figures. The caller must always show the
//    result as an editable, pre-filled form — never auto-save it.

/**
 * Decodes a PDF-style (Adobe variant) ASCII85 stream: groups of 5 chars in
 * '!'..'u' become 4 bytes via base-85, 'z' alone is four zero bytes, and a
 * trailing '~>' end marker (if present) is stripped first.
 */
function pdf_ascii85_decode(string $s): string
{
    $s = preg_replace('/\s+/', '', $s) ?? $s;
    $end = strpos($s, '~>');
    if ($end !== false) $s = substr($s, 0, $end);
    $out = '';
    $len = strlen($s);
    $i = 0;
    $group = '';
    while ($i < $len) {
        $c = $s[$i];
        if ($c === 'z' && $group === '') { $out .= "\0\0\0\0"; $i++; continue; }
        $group .= $c;
        if (strlen($group) === 5) {
            $out .= pdf_ascii85_group_decode($group, 4);
            $group = '';
        }
        $i++;
    }
    if ($group !== '') {
        $n = strlen($group) - 1; // bytes this partial group represents
        $group = str_pad($group, 5, 'u');
        $out .= substr(pdf_ascii85_group_decode($group, 4), 0, $n);
    }
    return $out;
}

function pdf_ascii85_group_decode(string $group, int $byteCount): string
{
    $n = 0;
    for ($k = 0; $k < 5; $k++) $n = $n * 85 + (ord($group[$k]) - 33);
    // Big-endian: most significant byte (k=3) first.
    $bytes = chr(($n >> 24) & 0xFF) . chr(($n >> 16) & 0xFF) . chr(($n >> 8) & 0xFF) . chr($n & 0xFF);
    return substr($bytes, 0, $byteCount);
}

/** Decompresses every FlateDecode stream it can find (optionally ASCII85-wrapped) and concatenates the result. */
function pdf_raw_streams(string $bytes): string
{
    $out = '';
    $offset = 0;
    while (($streamPos = strpos($bytes, 'stream', $offset)) !== false) {
        // The dictionary for this stream is whatever precedes "stream" back to
        // the nearest "obj" — look there for a Flate filter before decoding.
        $dictStart = strrpos(substr($bytes, 0, $streamPos), 'obj');
        $dict = $dictStart !== false ? substr($bytes, $dictStart, $streamPos - $dictStart) : '';
        $isFlate = stripos($dict, '/FlateDecode') !== false;
        $isAscii85 = stripos($dict, '/ASCII85Decode') !== false;
        // Any OTHER named filter (DCTDecode/CCITTFaxDecode/JPXDecode/JBIG2Decode —
        // all image codecs, never text) means this stream is binary image data,
        // not content to read as text, even once decoded. Treating it as plain
        // bytes (the old behaviour) let raw JPEG noise that happened to contain
        // the ASCII bytes "Tj"/"TJ"/"Tm" leak into the extracted "text".
        $hasOtherFilter = (!$isFlate && !$isAscii85 && preg_match('/\/Filter\b/', $dict) === 1)
            || (preg_match('/\/Filter\s*\[[^\]]*\]/', $dict, $fm) === 1 && preg_match('/\/(DCTDecode|CCITTFaxDecode|JPXDecode|JBIG2Decode)\b/', $fm[0]) === 1);
        // A flate-compressed raster image (e.g. a scanned page saved with
        // /Filter /FlateDecode rather than a DCT/JPX codec) declares no
        // image-specific filter name at all, so the check above misses it —
        // confirmed against a real 9.6MB policy PDF whose single largest
        // stream decompressed to ~61MB of raw bitmap data and exhausted
        // PHP's memory limit. Its dict's own /Subtype /Image catches this
        // case regardless of which filter was used.
        $isImage = preg_match('/\/Subtype\s*\/Image\b/', $dict) === 1;
        // An embedded font PROGRAM (FontFile/FontFile2/FontFile3 — the actual
        // TrueType/CFF binary a font's glyphs are drawn from) is routinely
        // FlateDecode-compressed too, same as a genuine content stream, and
        // its internal name tables often contain readable ASCII (font family
        // names etc.) — confirmed against a real policy PDF where this
        // leaked in as what looked like page text and produced a false
        // insurer-name match. Its dict always declares which font slot it
        // fills, which a real content stream's dict never does.
        $isFontFile = preg_match('/\/FontFile[0-9]?\b/', $dict) === 1;

        // Stream data starts right after the "stream" keyword's end-of-line
        // (CRLF or LF) and ends at the matching "endstream".
        $dataStart = $streamPos + strlen('stream');
        if (substr($bytes, $dataStart, 2) === "\r\n") $dataStart += 2;
        elseif (substr($bytes, $dataStart, 1) === "\n") $dataStart += 1;
        $endPos = strpos($bytes, 'endstream', $dataStart);
        if ($endPos === false) break;
        $raw = substr($bytes, $dataStart, $endPos - $dataStart);

        if ($isFlate && !$isImage && !$isFontFile) {
            if ($isAscii85) $raw = pdf_ascii85_decode($raw);
            // Belt-and-braces even with the /Subtype /Image check above: cap
            // how much any single stream is allowed to inflate to. A real
            // page of policy text never approaches this; an image that
            // slipped past the dict check (or any other unbounded stream)
            // is discarded rather than risk exhausting the memory limit.
            $maxLen = 8_000_000;
            $decoded = @gzuncompress($raw, $maxLen);
            if ($decoded === false) {
                // Some writers omit the 2-byte zlib header's checksum trailer or
                // pad the stream; gzinflate (raw deflate, skip the zlib header)
                // is worth a second try before giving up on this stream.
                $decoded = @gzinflate(substr($raw, 2), $maxLen);
            }
            // Same "does this actually look like page content" gate the
            // no-filter branch below already applies — a content stream is
            // never the only kind of thing that's FlateDecode-compressed
            // (font programs, ICC colour profiles and XMP metadata all are
            // too, and aren't reliably caught by dict checks alone), so
            // never trust the filter name on its own.
            if ($decoded !== false && preg_match('/\b(Tj|TJ|Td|Tm)\b/', $decoded)) $out .= $decoded . "\n";
        } elseif (!$hasOtherFilter && !$isImage && !$isFontFile) {
            // No /Filter at all means genuinely raw bytes — almost always an
            // uncompressed content stream, occasionally raw font/embedded-file
            // data, so still gate on it actually looking like page content.
            if (preg_match('/\b(Tj|TJ|Td|Tm)\b/', $raw)) $out .= $raw . "\n";
        }
        // else: an image codec (DCTDecode/CCITTFaxDecode/JPXDecode/…) —
        // skipped; this reader has no OCR, so it has nothing to do with these.
        $offset = $endPos + strlen('endstream');
    }
    return $out;
}

/** Un-escapes a PDF literal string's \( \) \\ and \ddd octal sequences. */
function pdf_unescape_literal(string $s): string
{
    return preg_replace_callback('/\\\\([()\\\\nrtbf]|[0-7]{1,3})/', function ($m) {
        $esc = $m[1];
        $map = ['n' => "\n", 'r' => "\r", 't' => "\t", 'b' => "\x08", 'f' => "\x0c", '(' => '(', ')' => ')', '\\' => '\\'];
        if (isset($map[$esc])) return $map[$esc];
        return chr(octdec($esc) & 0xFF);
    }, $s);
}

function pdf_hex_to_str(string $hex): string
{
    $hex = preg_replace('/[^0-9A-Fa-f]/', '', $hex);
    if (strlen($hex) % 2 !== 0) $hex .= '0';
    return hex2bin($hex) ?: '';
}

/**
 * Turns a fully byte-unescaped string operand into text. With no CMap this
 * is a no-op (the caller's final WinAnsi pass handles single-byte text);
 * with a CMap (any font carrying its own /ToUnicode — see
 * pdf_find_tounicode_cmaps) bytes are read $byteWidth at a time (1 byte for
 * an ordinary simple font's custom glyph codes, 2 for a CID/Identity-H
 * composite font — real PDFs use both) and looked up individually. A code
 * with no ToUnicode entry is skipped outright rather than guessed — there
 * is no font program here to fall back on.
 */
function pdf_decode_string_bytes(string $bytes, ?array $cmap, int $byteWidth = 2): string
{
    if ($cmap === null) return $bytes;
    $out = '';
    $len = strlen($bytes);
    for ($i = 0; $i + $byteWidth <= $len; $i += $byteWidth) {
        $code = 0;
        for ($k = 0; $k < $byteWidth; $k++) $code = ($code << 8) | ord($bytes[$i + $k]);
        if (isset($cmap[$code])) {
            $out .= pdf_codepoints_to_utf8($cmap[$code]);
        } elseif ($byteWidth === 1 && $code > 0) {
            $out .= chr($code); // best-effort WinAnsi fallback for an un-mapped low code
        }
    }
    return $out;
}

function pdf_codepoints_to_utf8(array $codepoints): string
{
    $s = '';
    foreach ($codepoints as $cp) {
        if ($cp <= 0) continue; // ToUnicode sometimes maps a code to U+0000 for "no visible glyph"
        $s .= function_exists('mb_chr') ? (mb_chr($cp, 'UTF-8') ?: '') : pdf_utf8_encode_codepoint($cp);
    }
    return $s;
}

function pdf_utf8_encode_codepoint(int $cp): string
{
    if ($cp < 0x80) return chr($cp);
    if ($cp < 0x800) return chr(0xC0 | ($cp >> 6)) . chr(0x80 | ($cp & 0x3F));
    if ($cp < 0x10000) return chr(0xE0 | ($cp >> 12)) . chr(0x80 | (($cp >> 6) & 0x3F)) . chr(0x80 | ($cp & 0x3F));
    return chr(0xF0 | ($cp >> 18)) . chr(0x80 | (($cp >> 12) & 0x3F)) . chr(0x80 | (($cp >> 6) & 0x3F)) . chr(0x80 | ($cp & 0x3F));
}

/** @return array<int,int[]> PDF character code => one or more Unicode codepoints */
function pdf_hex_to_codepoints(string $hex): array
{
    $hex = preg_replace('/\s+/', '', $hex) ?? $hex;
    $cps = [];
    // The destination is one or more consecutive UTF-16BE code units (4 hex
    // digits each) — astral (surrogate-pair) codepoints are not reassembled,
    // which is fine for the Latin/₹/typographic text real policy PDFs use.
    for ($i = 0; $i + 4 <= strlen($hex); $i += 4) $cps[] = (int) hexdec(substr($hex, $i, 4));
    return $cps ?: [0];
}

/**
 * Parses one ToUnicode CMap's codespacerange (to learn its byte width — 1
 * byte for a simple font's own custom encoding, 2 for a CID/Identity-H
 * composite font; real PDFs use both, not just the latter) and its
 * bfchar/bfrange blocks (code => one or more Unicode codepoints).
 *
 * @return array{byte_width: int, map: array<int,int[]>}
 */
function pdf_parse_one_cmap(string $cmapText): array
{
    $byteWidth = 1;
    if (preg_match('/begincodespacerange\s*<([0-9A-Fa-f]+)>/', $cmapText, $m)) {
        $byteWidth = (int) (strlen($m[1]) / 2) ?: 1;
    }
    $map = [];
    if (preg_match_all('/beginbfchar(.*?)endbfchar/s', $cmapText, $blocks)) {
        foreach ($blocks[1] as $block) {
            if (preg_match_all('/<([0-9A-Fa-f]+)>\s*<([0-9A-Fa-f]+)>/', $block, $pairs, PREG_SET_ORDER)) {
                foreach ($pairs as $p) {
                    $map[(int) hexdec($p[1])] = pdf_hex_to_codepoints($p[2]);
                }
            }
        }
    }
    if (preg_match_all('/beginbfrange(.*?)endbfrange/s', $cmapText, $blocks)) {
        foreach ($blocks[1] as $block) {
            // Array destination form: <lo> <hi> [ <d1> <d2> ... ] — one explicit
            // mapping per code in the range, in order.
            if (preg_match_all('/<([0-9A-Fa-f]+)>\s*<([0-9A-Fa-f]+)>\s*\[(.*?)\]/s', $block, $arr, PREG_SET_ORDER)) {
                foreach ($arr as $t) {
                    $lo = (int) hexdec($t[1]);
                    $hi = (int) hexdec($t[2]);
                    preg_match_all('/<([0-9A-Fa-f]+)>/', $t[3], $dm);
                    $code = $lo;
                    foreach ($dm[1] as $d) {
                        if ($code > $hi) break;
                        $map[$code] = pdf_hex_to_codepoints($d);
                        $code++;
                    }
                }
                $block = preg_replace('/<([0-9A-Fa-f]+)>\s*<([0-9A-Fa-f]+)>\s*\[(.*?)\]/s', '', $block) ?? $block;
            }
            // Scalar form: <lo> <hi> <dstLo> — dstLo increments by (code - lo).
            if (preg_match_all('/<([0-9A-Fa-f]+)>\s*<([0-9A-Fa-f]+)>\s*<([0-9A-Fa-f]+)>/', $block, $triples, PREG_SET_ORDER)) {
                foreach ($triples as $t) {
                    $lo = (int) hexdec($t[1]);
                    $hi = (int) hexdec($t[2]);
                    $dst = pdf_hex_to_codepoints($t[3]);
                    $lastUnit = array_pop($dst);
                    for ($code = $lo; $code <= $hi; $code++) {
                        $map[$code] = array_merge($dst, [$lastUnit + ($code - $lo)]);
                    }
                }
            }
        }
    }
    return ['byte_width' => $byteWidth, 'map' => $map];
}

/**
 * Scans the whole file for every ToUnicode CMap stream — every embedded
 * subset font with a non-standard encoding carries its own, whether it's a
 * CID/Identity-H composite font (2-byte codes) or an ordinary simple font
 * remapped to compact glyph indices (1-byte codes — just as common in
 * practice). Identified by content, not by resolving indirect object
 * references, since this reader never builds a full object graph.
 *
 * @return array{count: int, cmaps: list<array{byte_width:int, map:array<int,int[]>}>}
 */
function pdf_find_tounicode_cmaps(string $bytes): array
{
    $cmaps = [];
    $offset = 0;
    while (($streamPos = strpos($bytes, 'stream', $offset)) !== false) {
        $dictStart = strrpos(substr($bytes, 0, $streamPos), 'obj');
        $dict = $dictStart !== false ? substr($bytes, $dictStart, $streamPos - $dictStart) : '';
        $isFlate = stripos($dict, '/FlateDecode') !== false;
        $isAscii85 = stripos($dict, '/ASCII85Decode') !== false;
        $dataStart = $streamPos + strlen('stream');
        if (substr($bytes, $dataStart, 2) === "\r\n") $dataStart += 2;
        elseif (substr($bytes, $dataStart, 1) === "\n") $dataStart += 1;
        $endPos = strpos($bytes, 'endstream', $dataStart);
        if ($endPos === false) break;
        $raw = substr($bytes, $dataStart, $endPos - $dataStart);
        $offset = $endPos + strlen('endstream');
        // A CMap is always a small, plain-text PostScript-like resource —
        // skip anything implausibly large (never legitimately a CMap) before
        // even attempting to decompress it, so a mis-tagged multi-megabyte
        // image stream can't exhaust memory here the way one did against a
        // real 9MB sample during testing.
        if (!$isFlate || strlen($raw) > 200_000) continue;
        if ($isAscii85) $raw = pdf_ascii85_decode($raw);
        $decoded = @gzuncompress($raw);
        if ($decoded === false) $decoded = @gzinflate(substr($raw, 2));
        if ($decoded === false || strpos($decoded, 'begincmap') === false) continue;
        $cmaps[] = pdf_parse_one_cmap($decoded);
    }
    return ['count' => count($cmaps), 'cmaps' => $cmaps];
}

/** Pulls every Tj/TJ text-showing operator's string content out of a decoded content stream, in order. */
function pdf_extract_text_from_content(string $content, ?array $cmap = null, int $byteWidth = 2): string
{
    $out = [];
    // (literal string) Tj  — single string shown as-is.
    // [(string) -120 (string) ...] TJ — an array of strings (numbers are kerning, skipped).
    $len = strlen($content);
    $i = 0;
    $lastWasSpace = true;
    while ($i < $len) {
        $ch = $content[$i];
        if ($ch === '(') {
            // Scan a balanced, escape-aware literal string.
            $depth = 1;
            $j = $i + 1;
            $buf = '';
            while ($j < $len && $depth > 0) {
                $c = $content[$j];
                if ($c === '\\' && $j + 1 < $len) {
                    $buf .= $c . $content[$j + 1];
                    $j += 2;
                    continue;
                }
                if ($c === '(') $depth++;
                elseif ($c === ')') { $depth--; if ($depth === 0) { $j++; break; } }
                $buf .= $c;
                $j++;
            }
            $text = pdf_decode_string_bytes(pdf_unescape_literal($buf), $cmap, $byteWidth);
            if ($text !== '') { $out[] = $text; $lastWasSpace = false; }
            $i = $j;
            continue;
        }
        if ($ch === '<' && ($i + 1 >= $len || $content[$i + 1] !== '<')) {
            $j = strpos($content, '>', $i + 1);
            if ($j === false) break;
            $text = pdf_decode_string_bytes(pdf_hex_to_str(substr($content, $i + 1, $j - $i - 1)), $cmap, $byteWidth);
            if ($text !== '') { $out[] = $text; $lastWasSpace = false; }
            $i = $j + 1;
            continue;
        }
        // A run of numbers inside a TJ array is a kerning adjustment, not text —
        // large negative values in particular often stand in for a real space
        // the content stream never spells out as its own string.
        if ($ch === '-' || ctype_digit($ch)) {
            $j = $i;
            while ($j < $len && (ctype_digit($content[$j]) || in_array($content[$j], ['-', '.'], true))) $j++;
            $num = (float) substr($content, $i, $j - $i);
            if ($num < -80 && !$lastWasSpace) { $out[] = ' '; $lastWasSpace = true; }
            $i = $j;
            continue;
        }
        // A line break between text-showing operators (Td/TD/T*/ET) reads as a
        // real line break — insurer schedules are mostly label: value lines,
        // and losing those breaks would run every line into the last.
        if (preg_match('/\G(Td|TD|T\*|ET)\b/', $content, $m, 0, $i)) {
            $out[] = "\n";
            $lastWasSpace = true;
            $i += strlen($m[0]);
            continue;
        }
        $i++;
    }
    $text = implode('', $out);
    // With a CMap, each string already went through pdf_decode_string_bytes
    // and is proper UTF-8 — re-running a Windows-1252 fixup over that would
    // corrupt its multi-byte sequences. Only the no-CMap (1-byte WinAnsi)
    // path needs this pass.
    if ($cmap === null) $text = pdf_winansi_to_utf8($text);
    $text = preg_replace('/[ \t]+/', ' ', $text);
    $text = preg_replace('/\n{3,}/', "\n\n", $text);
    return trim($text);
}

/**
 * Most PDF fonts built from Type1/TrueType with the common WinAnsiEncoding
 * show high bytes (0x80-0xFF) as Windows-1252 code points, not raw Unicode
 * or UTF-8 — left alone, an em-dash or curly quote in the source document
 * decodes to a single invalid-UTF-8 byte and renders as a replacement
 * character. This only affects display text (headings, labels); none of
 * the regex-based field guesses above depend on these characters.
 */
function pdf_winansi_to_utf8(string $s): string
{
    if (!preg_match('/[\x80-\xFF]/', $s)) return $s; // already plain ASCII, skip the pass
    return @iconv('Windows-1252', 'UTF-8//IGNORE', $s) ?: $s;
}

/** @return array{text:string, low_confidence:bool} */
function pdf_extract_text(string $bytes): array
{
    $decoded = pdf_raw_streams($bytes);
    // A huge share of real insurer PDFs embed subset fonts with their own
    // non-standard glyph encoding — NOT WinAnsi/ASCII — whether that's a
    // CID/Identity-H composite font (2-byte codes) or an ordinary simple
    // font remapped to compact 1-byte codes (confirmed against two real,
    // user-supplied policy PDFs: one of each kind). Those PDFs are
    // unreadable without each font's own /ToUnicode CMap, so detection is
    // keyed on /ToUnicode being present at all, not on Identity-H
    // specifically — see pdf_decode_string_bytes().
    $cmap = null;
    $byteWidth = 2;
    $unsafeMultiFontCid = false;
    // NOTE: this deliberately does NOT gate on the literal string "ToUnicode"
    // appearing anywhere in the raw file first. A real policy PDF using
    // PDF 1.5+ compressed object streams (ObjStm) has every /Font dict's
    // /ToUnicode *key* compressed away along with the rest of that object —
    // the plain string genuinely isn't present anywhere outside the
    // ObjStm — even though the CMap *stream* it points to is still an
    // ordinary, independently-discoverable "stream"..."endstream" block.
    // Gating on that string silently skipped CMap detection entirely for
    // such a file, falling through to the raw WinAnsi path and producing
    // confidently-wrong garbled text (worse than the multi-font case below,
    // since nothing flagged it low_confidence) — confirmed against a real
    // 9.6MB sample. pdf_find_tounicode_cmaps() finds CMaps by content, so
    // it costs nothing to just always run it.
    $found = pdf_find_tounicode_cmaps($bytes);
    if ($found['count'] === 1) {
        $cmap = $found['cmaps'][0]['map'];
        $byteWidth = $found['cmaps'][0]['byte_width'];
    } elseif ($found['count'] > 1) {
        // Two or more embedded subset fonts, each free to reuse the same
        // code for a DIFFERENT character — merging their CMaps into one
        // table silently produces plausible-looking wrong text (confirmed
        // against a real multi-font policy PDF: a heading decoded correctly
        // by chance, but body text came out as readable-looking garbage,
        // including a false "LIC" match inside the word "policy"). There is
        // no reliable way to tell which font applies to which string
        // without resolving the content stream's font-selection (Tf)
        // operators against each font's own resource dictionary, which this
        // reader does not do. Refusing to guess is safer than showing
        // confidently wrong financial data.
        $unsafeMultiFontCid = true;
    }
    // $found['count'] === 0 means no embedded CMap exists at all — either a
    // genuinely simple WinAnsi-encoded PDF (the common case; fall through
    // normally) or a CID font with no ToUnicode and no font program this
    // reader can resolve glyphs from either way (an acknowledged gap).
    $text = $unsafeMultiFontCid ? '' : pdf_extract_text_from_content($decoded, $cmap, $byteWidth);
    // Fewer than ~40 characters out of a real policy document means this PDF
    // almost certainly uses a layout this reader doesn't understand (a scan,
    // or compressed object streams) — say so rather than parse noise.
    return ['text' => $text, 'low_confidence' => $unsafeMultiFontCid || strlen($text) < 40];
}

// ---------------------------------------------------------------------------
// Field-guessing heuristics. Every one of these is a best-effort regex over
// human-readable text — never trust a money or date field here without the
// caller showing it to a person first. `null` means "not found", not zero.

const PDF_KNOWN_INSURERS = [
    'TATA AIA', 'TATA AIG', 'HDFC ERGO', 'HDFC Life', 'ICICI Lombard', 'ICICI Prudential Life',
    'ICICI Prudential', 'Bajaj Allianz', 'Star Health', 'Niva Bupa', 'Care Health', 'Religare Health',
    'New India Assurance', 'Oriental Insurance', 'United India Insurance', 'National Insurance',
    'Reliance General', 'SBI Life', 'SBI General', 'Max Life', 'Max Bupa', 'Kotak Mahindra Life',
    'Kotak Life', 'LIC', 'Life Insurance Corporation', 'Aditya Birla Health', 'ManipalCigna',
    'Future Generali', 'Shriram Life', 'Bharti AXA', 'Edelweiss Tokio', 'PNB MetLife', 'Aegon Life',
    'HDFC Mutual Fund', 'SBI Mutual Fund', 'Axis Mutual Fund', 'ICICI Prudential MF', 'Nippon India MF',
    'Kotak Mutual Fund', 'UTI Mutual Fund', 'Franklin Templeton',
];

function pdf_guess_insurer(string $text): ?string
{
    foreach (PDF_KNOWN_INSURERS as $name) {
        // Word-boundary, not stripos: a short abbreviation like "LIC" would
        // otherwise match inside an ordinary word (po-LIC-y) and misreport
        // the insurer — caught against a real sample PDF during testing.
        if (preg_match('/\b' . preg_quote($name, '/') . '\b/i', $text)) return $name;
    }
    return null;
}

function pdf_find_after_label(string $text, array $labels): ?string
{
    foreach ($labels as $label) {
        // "<label> ... : <value up to end of line>" — colon optional, a little
        // punctuation/whitespace between label and value is normal.
        if (preg_match('/' . preg_quote($label, '/') . '\s*[:\-]?\s*([^\n]{1,60})/i', $text, $m)) {
            $val = trim($m[1]);
            if ($val !== '') return $val;
        }
    }
    return null;
}

function pdf_guess_policy_number(string $text): ?string
{
    $val = pdf_find_after_label($text, ['Policy No.', 'Policy No', 'Policy Number']);
    if (!$val) return null;
    // Keep just the leading token-like run (letters/digits/hyphens/slashes) —
    // don't drag in the rest of the line if the regex above over-matched.
    preg_match('/^[A-Za-z0-9\/\-]{4,40}/', $val, $m);
    return $m[0] ?? $val;
}

function pdf_money_near_label(string $text, array $labels): ?float
{
    foreach ($labels as $label) {
        if (preg_match('/' . preg_quote($label, '/') . '[^\n0-9₹]{0,20}(?:₹|Rs\.?|INR)?\s*([0-9][0-9,]{2,})(?:\.\d+)?/i', $text, $m)) {
            $num = (float) str_replace(',', '', $m[1]);
            if ($num > 0) return $num;
        }
    }
    return null;
}

function pdf_parse_date(string $raw): ?string
{
    $raw = trim($raw);
    $months = ['Jan' => 1, 'Feb' => 2, 'Mar' => 3, 'Apr' => 4, 'May' => 5, 'Jun' => 6, 'Jul' => 7, 'Aug' => 8, 'Sep' => 9, 'Oct' => 10, 'Nov' => 11, 'Dec' => 12];
    if (preg_match('/^(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})$/', $raw, $m)) {
        return sprintf('%04d-%02d-%02d', (int) $m[3], (int) $m[2], (int) $m[1]);
    }
    if (preg_match('/^(\d{1,2})[\-\s]([A-Za-z]{3,9})[\-\s](\d{4})$/', $raw, $m)) {
        $mon = $months[substr(ucfirst(strtolower($m[2])), 0, 3)] ?? null;
        if ($mon) return sprintf('%04d-%02d-%02d', (int) $m[3], $mon, (int) $m[1]);
    }
    if (preg_match('/^(\d{4})-(\d{2})-(\d{2})$/', $raw)) return $raw;
    return null;
}

function pdf_date_near_label(string $text, array $labels): ?string
{
    foreach ($labels as $label) {
        if (preg_match('/' . preg_quote($label, '/') . '[^\n0-9]{0,20}(\d{1,2}[\/\-\s][A-Za-z0-9]{2,9}[\/\-\s]\d{4})/i', $text, $m)) {
            $d = pdf_parse_date($m[1]);
            if ($d) return $d;
        }
    }
    return null;
}

const PDF_PRODUCT_KEYWORDS = [
    'Mutual Fund' => ['SIP', 'Mutual Fund', 'Folio'],
    'Family Mediclaim' => ['Mediclaim', 'Family Health', 'Floater'],
    'Critical Illness Cover' => ['Critical Illness'],
    'Group Health Cover' => ['Group Health', 'Group Mediclaim'],
    'Child Education Plan' => ['Child Education', "Child's Future", 'Education Plan'],
    'Guaranteed Return Plan' => ['Guaranteed Return', 'Endowment', 'Money Back'],
    'Pension/Annuity' => ['Pension', 'Annuity', 'Retirement'],
    'Keyman Insurance' => ['Keyman', 'Key Man'],
    'General Insurance' => ['Motor Insurance', 'Fire Insurance', 'Marine Insurance', 'Shop Insurance', 'Property Insurance'],
    'Pure Term Plan' => ['Term Plan', 'Term Assurance', 'Term Insurance'],
];

function pdf_guess_product_type(string $text): ?string
{
    foreach (PDF_PRODUCT_KEYWORDS as $productType => $keywords) {
        foreach ($keywords as $kw) {
            if (stripos($text, $kw) !== false) return $productType;
        }
    }
    return null;
}

/**
 * The insured/proposer's name — used only by the bulk ZIP import
 * (bulk_policy_import.php) to suggest which existing client record a given
 * PDF belongs to. Never auto-saved on its own; always a suggestion a human
 * confirms, same as every other guessed field here.
 */
function pdf_guess_insured_name(string $text): ?string
{
    $val = pdf_find_after_label($text, [
        'Insured Name', 'Name of the Life Assured', 'Life Assured Name', 'Life Assured',
        'Proposer Name', 'Name of Proposer', 'Policyholder Name', "Policy Holder's Name",
        'Name of the Policyholder', 'Customer Name',
    ]);
    if (!$val) return null;
    // Keep just the name-like leading run — letters/spaces/periods/apostrophes —
    // so a label regex over-match (e.g. trailing "DOB: 01/01/1990" on the
    // same line) doesn't get treated as part of the name.
    preg_match("/^[A-Za-z][A-Za-z.' ]{1,60}/", $val, $m);
    $name = isset($m[0]) ? trim($m[0]) : null;
    return $name !== '' ? $name : null;
}

/** @return array<string,mixed> */
function pdf_guess_policy_fields(string $text): array
{
    return [
        'insurer' => pdf_guess_insurer($text),
        'product_type' => pdf_guess_product_type($text),
        'policy_number' => pdf_guess_policy_number($text),
        'sum_assured' => pdf_money_near_label($text, ['Sum Assured', 'Sum Insured', 'Basic Sum Assured']),
        'premium' => pdf_money_near_label($text, ['Total Premium', 'Annual Premium', 'Instalment Premium', 'Premium Amount', 'Premium Payable']),
        'start_date' => pdf_date_near_label($text, ['Date of Commencement', 'Commencement Date', 'Risk Commencement Date', 'Policy Start Date', 'Date of Issue']),
        'renewal_date' => pdf_date_near_label($text, ['Date of Expiry', 'Policy End Date', 'Next Premium Due Date', 'Due Date', 'Renewal Date', 'Valid Upto']),
        'insured_name' => pdf_guess_insured_name($text),
    ];
}
