import {
  LayoutDashboard,
  TrendingUp,
  Users,
  UserPlus,
  ShieldAlert,
  ListChecks,
  Target,
  PhoneCall,
  History,
  Settings,
  BarChart3,
  HeartPulse,
  Trophy,
  BellRing,
  type LucideIcon,
} from "lucide-react";

export const adminNavItems: { label: string; href: string; group?: string; icon: LucideIcon }[] = [
  { label: "Dashboard", href: "/admin", icon: LayoutDashboard },
  { label: "Leads Desk", href: "/admin/leads", group: "Pipeline", icon: TrendingUp },
  { label: "My Clients", href: "/admin/clients", group: "Pipeline", icon: Users },
  { label: "Onboarding", href: "/admin/team", group: "Pipeline", icon: UserPlus },
  { label: "Claim Desk", href: "/admin/claims", group: "Pipeline", icon: ShieldAlert },
  { label: "Intimations", href: "/admin/intimations", group: "Pipeline", icon: BellRing },
  { label: "Tasks", href: "/admin/tasks", group: "Work", icon: ListChecks },
  { label: "Business Planning", href: "/admin/business-planning", group: "Work", icon: Target },
  { label: "Pivot Explorer", href: "/admin/analytics", group: "Work", icon: BarChart3 },
  { label: "Retention", href: "/admin/retention", group: "Work", icon: HeartPulse },
  { label: "Scorecards", href: "/admin/scorecard", group: "Work", icon: Trophy },
  { label: "Telephony & AI Calling", href: "/admin/telephony", group: "System", icon: PhoneCall },
  { label: "Audit Log", href: "/admin/audit-log", group: "System", icon: History },
  { label: "Settings", href: "/admin/settings", group: "System", icon: Settings },
];
